---
- hosts: windowsserver
  tasks:
    - name: Change ssh port to 5986
      set_fact:
        ansible_port: 5986
    - name: Install Apache2 
      win_chocolatey:
        name: apache-httpd 
        state: present 
        package_params:
          AdditionalTools: yes

