---
- hosts: windowsserver
  tasks:
    - name: Change ssh port to 5986
      set_fact:
        ansible_port: 5986
      gather_facts: false
  tasks:
    - name: Download simple web site to 'C:\inetpub\wwwroot\ansible.html'
      win_get_url:
        url: 'https://raw.githubusercontent.com/thisdavejohnson/mywebapp/master/index.html'
        dest: 'C:\inetpub\wwwroot\ansible.html'
