---
- hosts: windowsserver
  tasks:
    - name: Change ssh port to 5986
      set_fact:
        ansible_port: 5986
      gather_facts: false
  tasks:
    - name: Download simple web site to 'C:\inetpub\wwwroot\ansible.html'
      win_copy:
        src: ./files/multipurpose
        dest: C:\inetpub\wwwroot\
