---
- hosts: windowsserver 
  tasks:
    - name: Change ssh port to 5986
      set_fact:
        ansible_port: 5986  
    - name: Install Chocolatey
      raw: Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
    - name: Ensure the required NuGet package provider version is installed
      win_shell: Find-PackageProvider -Name Nuget -ForceBootstrap -IncludeDependencies -Force
    - name: Install NUnit
      win_chocolatey:
        name: nunit-console-runner
        state: present
        package_params:
          AdditionalTools: yes
    - name: Install .net framework 
      win_chocolatey:
        name: dotnet4.5 
        state: present
        package_params:
          AdditionalTools: yes      
    - name: Ensure IIS is installed
      win_feature:
        name: Web-Server
        state: present
