---
- hosts: windowsserver
  tasks:
    - name: Change ssh port to 5986
      set_fact:
        ansible_port: 5986
    - name: check downloaded file exists
      win_stat:
         path: c:\sql17\sql_installer.exe
      register: installer_file
    - name: get the installer
      win_get_url:
           url: 'https://download.microsoft.com/download/5/E/9/5E9B18CC-8FD5-467E-B5BF-BADE39C51F73/SQLServer2017-SSEI-Expr.exe'
           dest: 'c:\sql17\sql_installer.exe'
      when: not installer_file.stat.exists
    - name: Install the database
      win_command: c:\sql17\sql_installer.exe /configurationfile=c:\sql17\sql_conf.ini
      args:
        chdir: c:\sql17
