---
- hosts: windowsserver
  tasks:
    - name: Change ssh port to 5986
      set_fact:
        ansible_port: 5986
    - name: Install Xampp 
      win_chocolatey:
        name: bitnami-xampp 
        state: present
        package_params:
          AdditionalTools: yes
